-- Generated from lib/features/spots/data/spots_data.dart
-- Run this after schema_tourist_spots.sql

insert into public.tourist_spots (
  id, name, description, latitude, longitude, category, image_url, user_images, status,
  price_range, contact_phone, contact_email, promotional_message, is_featured
)
values
(
  '1',
  'Swayambhunath Stupa',
  'Ancient religious architecture atop a hill in the Kathmandu Valley. often referred to as the Monkey Temple.',
  27.7149,
  85.2903,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Swayambhunath_Temple-2022.jpg/800px-Swayambhunath_Temple-2022.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '2',
  'Kathmandu Durbar Square',
  'Historic seat of Nepalese royalty, featuring stunning Newari architecture and ancient temples.',
  27.7042,
  85.306,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Kathmandu_Durbar_Square_Pigeon.jpg/800px-Kathmandu_Durbar_Square_Pigeon.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '3',
  'Patan Durbar Square',
  'Renowned for its heritage of fine arts and classical Nepalese architecture.',
  27.6727,
  85.3253,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Patan_Durbar_Square_Panorama.jpg/800px-Patan_Durbar_Square_Panorama.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '4',
  'Bhaktapur Durbar Square',
  'The plaza in front of the royal palace of the old Bhaktapur Kingdom.',
  27.6715,
  85.4294,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Nyatapola_Temple%2C_Bhaktapur_Durbar_Square.jpg/800px-Nyatapola_Temple%2C_Bhaktapur_Durbar_Square.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '5',
  'Lumbini',
  'The birthplace of Siddhartha Gautama, the Lord Buddha.',
  27.4816,
  83.2766,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Maya_Devi_Temple_Lumbini.jpg/800px-Maya_Devi_Temple_Lumbini.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '6',
  'Gorkha Durbar',
  'The ancestral palace of the Shah dynasty built in the 16th century.',
  28.0051,
  84.6225,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Gorkha_Durbar_Palace.jpg/800px-Gorkha_Durbar_Palace.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '7',
  'Nuwakot Palace',
  'Historic seven-story palace built by Prithvi Narayan Shah.',
  27.9157,
  85.1614,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nuwakot_Durbar.jpg/800px-Nuwakot_Durbar.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '8',
  'Janaki Mandir',
  'Hindu temple dedicated to Goddess Sita, stunning Mughal architecture.',
  26.7303,
  85.9264,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Janaki_Mandir_Janakpur.jpeg/800px-Janaki_Mandir_Janakpur.jpeg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '9',
  'Tansen Durbar',
  'Ancient palace in the hills of Palpa.',
  27.8681,
  83.5658,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '10',
  'Changunarayan Temple',
  'The oldest Hindu temple in use in the Kathmandu Valley.',
  27.7161,
  85.4278,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '11',
  'Kirtipur Historic City',
  'Ancient Newar township with rich history and classic streets.',
  27.6781,
  85.2755,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '12',
  'Sindhuli Gadhi',
  'Historical fort where Gurkha soldiers defeated the British.',
  27.2797,
  85.9723,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '13',
  'Amar Narayan Temple',
  'Historic wooden temple in Tansen.',
  27.8654,
  83.5489,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '14',
  'Rani Mahal',
  'Often called the Taj Mahal of Nepal, situated by the Kali Gandaki river.',
  27.9407,
  83.5857,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '15',
  'Panauti Durbar',
  'Ancient square in the preserved Newari town of Panauti.',
  27.5833,
  85.5167,
  'historicalSites',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '16',
  'Pashupatinath Temple',
  'One of the most sacred Hindu temples of Nepal, on the banks of Bagmati.',
  27.7104,
  85.3487,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Pashupatinath_Temple-2019.jpg/800px-Pashupatinath_Temple-2019.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '17',
  'Muktinath Temple',
  'A sacred place for both Hindus and Buddhists in Mustang.',
  28.8153,
  83.8715,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '18',
  'Manakamana Temple',
  'Sacred place of the Hindu Goddess Bhagwati, an incarnation of Parvati.',
  27.9048,
  84.5828,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '19',
  'Gosainkunda Lake',
  'Alpine freshwater oligotrophic lake, sacred in Hinduism.',
  28.0827,
  85.4144,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '20',
  'Boudhanath Stupa',
  'One of the largest spherical stupas in Nepal, and a center of Tibetan Buddhism.',
  27.7215,
  85.362,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Boudhanath_Stupa_in_Kathmandu.jpg/800px-Boudhanath_Stupa_in_Kathmandu.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '21',
  'Pathibhara Devi',
  'Highly revered shrine in eastern Nepal.',
  27.4287,
  87.7788,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '22',
  'Budhanilkantha',
  'Large statue of sleeping Lord Vishnu carved from a single floating stone.',
  27.777,
  85.3639,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '23',
  'Dakshinkali Temple',
  'Dedicated to the goddess Kali, located in the south of Kathmandu.',
  27.6046,
  85.2599,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '24',
  'Devghat Dham',
  'Holistic center situated at the junction of Seti and Krishna Gandaki rivers.',
  27.7171,
  84.4316,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '25',
  'Tengboche Monastery',
  'Tibetan Buddhist monastery in the Khumbu valley.',
  27.8361,
  86.7644,
  'religiousPlaces',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '26',
  'Shivapuri Nagarjun National Park',
  'Protected area offering great nature trails and a quick escape from the city.',
  27.7979,
  85.3888,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Shivapuri_National_Park.jpg/800px-Shivapuri_National_Park.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '27',
  'Annapurna Base Camp Trek',
  'Legendary trekking route offering amphitheater views of the Himalayas.',
  28.53,
  83.878,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '28',
  'Everest Base Camp',
  'The iconic trek to the foot of the worlds highest mountain.',
  28.006,
  86.8524,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '29',
  'Langtang Valley Trek',
  'Beautiful valley known as the valley of glaciers.',
  28.2167,
  85.5667,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '30',
  'Chitwan National Park',
  'Dense forests offering elephant safaris and rhino spotting.',
  27.5341,
  84.4525,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '31',
  'Bardiya National Park',
  'Pristine conservation area famous for Bengal Tigers.',
  28.3949,
  81.2828,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '32',
  'Poon Hill Trek',
  'Short trek featuring incredible sunrise views over the Annapurna range.',
  28.4005,
  83.6885,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '33',
  'Rara Lake',
  'The largest fresh water lake in the Nepalese Himalayas.',
  29.5311,
  82.0784,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '34',
  'Phoksundo Lake',
  'Alpine fresh water oligotrophic lake in Shey Phoksundo National Park.',
  29.1983,
  82.9515,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '35',
  'Koshi Tappu Wildlife Reserve',
  'Famous for bird watching and the wild water buffalo.',
  26.6022,
  86.9934,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '36',
  'Makalu Barun National Park',
  'Remote national park with profound elevations and deep gorges.',
  27.7667,
  87.1167,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '37',
  'Khaptad National Park',
  'A hidden gem in the far west offering rolling green hills and peace.',
  29.3582,
  81.161,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '38',
  'Helambu Trek',
  'Accessible trekking region known for sweet apples and Buddhist culture.',
  28.0267,
  85.5097,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '39',
  'Manaslu Circuit',
  'Geographically spectacular and culturally fascinating mountain trek.',
  28.5497,
  84.5619,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '40',
  'Mardi Himal Trek',
  'A newly opened route offering stunning views of Machhapuchhre.',
  28.4554,
  83.8741,
  'natureTrails',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '41',
  'Nagarkot Viewpoint',
  'Village renowned for sunrise views of the Himalayas including Mount Everest.',
  27.7176,
  85.5218,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '42',
  'Sarangkot',
  'Famed for panoramic views of Annapurna, Dhaulagiri, and Machhapuchhre.',
  28.2439,
  83.9486,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '43',
  'Kala Patthar',
  'Offers the most accessible closeup view of Everest.',
  27.9959,
  86.8285,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '44',
  'Chandragiri Hills',
  'Cable car destination offering sweeping views of Kathmandu Valley.',
  27.6405,
  85.2039,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '45',
  'Kakani',
  'A quiet hill station offering views of the Ganesh Himal range.',
  27.8049,
  85.253,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '46',
  'Bandipur',
  'Preserved Newari town with stunning views of the Marsyangdi valley architecture.',
  27.9389,
  84.4172,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '47',
  'Dhulikhel Viewpoint',
  'Old Newari town offering excellent panoramic views of the snowy ranges.',
  27.6253,
  85.5222,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '48',
  'Phulchowki',
  'The highest hill in the Kathmandu Valley, great for hiking and bird watching.',
  27.5701,
  85.3995,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '49',
  'Gokyo Ri',
  'A peak offering a panoramic view of Everest and surrounding mountains.',
  27.9575,
  86.6833,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '50',
  'World Peace Pagoda Pokhara',
  'Massive Buddhist stupa on Ananda hill overlooking Phewa Lake.',
  28.2045,
  83.9431,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '51',
  'Tsum Valley',
  'A sacred Himalayan pilgrimage valley with ancient art and culture.',
  28.5333,
  84.9667,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '52',
  'Khopra Ridge',
  'Off-the-beaten-path viewpoint facing Mount Dhaulagiri.',
  28.49,
  83.7225,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '53',
  'Ilam Tea Gardens',
  'Lush green tea estates rolling over the hills of eastern Nepal.',
  26.9079,
  87.9252,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '54',
  'Namche Bazaar',
  'The gateway to the high Himalayas and Everest region.',
  27.8069,
  86.714,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '55',
  'Daman View Tower',
  'Offers the greatest unhindered view of the Himalayas from Dhaulagiri to Everest.',
  27.6,
  85.0833,
  'viewpoints',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '56',
  'Godawari Botanical Garden',
  'Lush gardens at the foot of Phulchowki hill, perfect for family picnics.',
  27.5935,
  85.3854,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '57',
  'Tribhuvan Park',
  'Large municipal park at Thankot, highly popular for weekend picnics.',
  27.6896,
  85.2078,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '58',
  'Kakani Picnic Spot',
  'Scenic picnic areas overlooking the central Himalayan ranges.',
  27.8105,
  85.259,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '59',
  'Taudaha Lake',
  'Peaceful lake area on the outskirts of Kathmandu, great for relaxing.',
  27.6433,
  85.2819,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '60',
  'Surya Chaur',
  'Beautiful grassy hill north of Kathmandu offering stunning mountain vistas.',
  27.8286,
  85.34,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '61',
  'Bhotechaur Tea Garden',
  'Known as "Mini Ilam", small tea estate perfect for photos and picnics.',
  27.8093,
  85.5097,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '62',
  'Sundarijal',
  'Forest river streams and waterfalls, a classic getaway spot.',
  27.7667,
  85.4167,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '63',
  'Panchakanya Park',
  'Lovely green space in Dharan, eastern Nepal.',
  26.8125,
  87.2783,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '64',
  'Begnas Lake',
  'Quiet and serene lake in Pokhara, less crowded than Phewa.',
  28.1692,
  84.0933,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '65',
  'Chobhar Gorge',
  'Historical gorge with picnic facilities and Jal Binayak temple nearby.',
  27.6528,
  85.2831,
  'picnicArea',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '66',
  'Shivapuri Cycling Trail',
  'Challenging uphill mountain biking trails through dense forest.',
  27.79,
  85.39,
  'cyclingSpots',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '67',
  'Mustang Offroad Route',
  'World-renowned arid valley trails specifically for 4x4 and adventure bikes.',
  29.1833,
  83.9667,
  'offroadRiding',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '68',
  'Changu Narayan MTB Trail',
  'Technical downhill and cross-country flow trails.',
  27.7121,
  85.4208,
  'cyclingSpots',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '69',
  'Pathilaya to Hetauda Highway',
  'A beloved stretching route famous among long-distance road cyclists.',
  27.0519,
  84.8805,
  'cyclingSpots',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '70',
  'Manang Valley Dirt Road',
  'Extreme offroading along the Marshyangdi river cliffs.',
  28.6667,
  84.0167,
  'offroadRiding',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '71',
  'Lubhu to Lele Trail',
  'Serene village roads perfect for weekend mountain biking.',
  27.618,
  85.3411,
  'cyclingSpots',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '72',
  'Kalinchowk 4x4 Trail',
  'Steep snow-covered dirt roads making for intense off-road drives in winter.',
  27.7333,
  86.0333,
  'offroadRiding',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '73',
  'Pharping to Kulekhani',
  'Long dirt and gravel climbs suitable for endurance cyclists.',
  27.6,
  85.1667,
  'cyclingSpots',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '74',
  'Ramechhap Ridge Ride',
  'Enduro bike trail offering scenic ridges and tough descents.',
  27.3235,
  86.0827,
  'offroadRiding',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '75',
  'Hattiban Downhill',
  'Dedicated downhill mountain biking track with jumps and berms.',
  27.6167,
  85.25,
  'cyclingSpots',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '76',
  'Mount Everest (Sagarmatha)',
  'The highest mountain peak in the world.',
  27.9881,
  86.925,
  'mountains',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '77',
  'Machhapuchhre (Fishtail)',
  'Iconic virgin peak dominating the Pokhara skyline.',
  28.495,
  83.9486,
  'mountains',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '78',
  'Annapurna Massif',
  'Spectacular mountain range featuring several peaks over 7,000m.',
  28.5961,
  83.8203,
  'mountains',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '79',
  'Ama Dablam',
  'Considered one of the most beautiful mountains in the Himalayas.',
  27.8611,
  86.8611,
  'mountains',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '80',
  'Dhaulagiri',
  'The seventh highest mountain in the world.',
  28.6975,
  83.4872,
  'mountains',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '81',
  'Upper Mustang Scenery',
  'Desert-like arid landscapes contrasting with white snow peaks.',
  29.1833,
  83.9667,
  'sceneries',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '82',
  'Khaptad Scenery',
  'Meadows and rolling green hills providing tranquil scenic beauty.',
  29.3582,
  81.161,
  'sceneries',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '83',
  'Gokyo Lakes',
  'World''s highest freshwater lake system with turquoise waters.',
  27.9533,
  86.6917,
  'sceneries',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '84',
  'Sankhuwasabha Cloud Forest',
  'Dense rhododendron forests covered in mystical fog.',
  27.5,
  87.25,
  'sceneries',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '85',
  'Manaslu Base Camp',
  'Awe-inspiring views beneath the eighth highest mountain.',
  28.55,
  84.5667,
  'sceneries',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '86',
  'Thamel Tourist Hub',
  'Kathmandu''s main spot for booking treks, tours, and expeditions.',
  27.7153,
  85.3123,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '87',
  'Pokhara Lakeside Info Center',
  'Central hub for Annapurna conservation permits and guides.',
  28.21,
  83.9575,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '88',
  'NTB Tourist Board',
  'Official Nepal Tourism Board office in Kathmandu.',
  27.7011,
  85.3175,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '89',
  'Lukla Guide Bureau',
  'For hiring guides and porters right after landing in the Everest region.',
  27.6861,
  86.7289,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '90',
  'Chitwan Safari Agencies',
  'Sauraha is packed with agencies booking jungle safaris.',
  27.5819,
  84.4819,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '91',
  'Mustang Permit Office',
  'Required office for crossing into the restricted Upper Mustang area.',
  28.7833,
  83.7167,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '92',
  'Bandipur Tourism Council',
  'Helpful local center for arranging homestays and tours.',
  27.9389,
  84.4172,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '93',
  'Lumbini Development Trust',
  'Provides maps and guides for the holy birthplace.',
  27.4816,
  83.2766,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '94',
  'Namche Visitor Center',
  'Sagarmatha National Park museum and information desk.',
  27.8069,
  86.714,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '95',
  'Tansen Tourist Office',
  'Local municipality guide booking setup in Palpa.',
  27.8681,
  83.5658,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '96',
  'Ilam Tourist Kiosk',
  'Information desk for navigating the tea estates.',
  26.9079,
  87.9252,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '97',
  'Bardia National Park Info',
  'Headquarters for securing tiger tracking guides.',
  28.3949,
  81.2828,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '98',
  'Langtang Park Checkpoint',
  'Must-stop agency checkpoint at Dhunche for valley trekkers.',
  28.1064,
  85.2975,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '99',
  'Gorkha Museum Guides',
  'For historical tours regarding the unification of Nepal.',
  28.0051,
  84.6225,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '100',
  'Janakpur Pilgrimage Center',
  'Arranges guides for exploring the various religious ponds and temples.',
  26.7303,
  85.9264,
  'touristAgents',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  NULL,
  NULL,
  NULL,
  NULL,
  false
),
(
  '101',
  'Yak & Yeti Hotel',
  'Luxury hotel in the heart of Kathmandu.',
  27.7126,
  85.3187,
  'hotels',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  '$$$',
  '+977-1-4248999',
  NULL,
  'Exclusive 20% off for Explore Nepal users!',
  true
),
(
  '102',
  'Nepal Airlines Ticketing',
  'Official flight ticketing office.',
  27.7001,
  85.3121,
  'tickets',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  '$$-$$$',
  '+977-1-4220757',
  NULL,
  'Book scenic mountain flights directly with us.',
  true
),
(
  '103',
  'Himalayan Guides Team',
  'Certified mountain guides for your trek.',
  27.7153,
  85.3102,
  'guides',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  '$$',
  '+977-9841234567',
  NULL,
  'Safe and guided tours to EBC and Annapurna.',
  false
),
(
  '104',
  'Thamel House Restaurant',
  'Authentic Nepali dining experience.',
  27.7171,
  85.3105,
  'dining',
  'https://upload.wikimedia.org/wikipedia/commons/e/ec/Himalaya_from_Nagarkot.jpg',
  '[]'::jsonb,
  'approved',
  '$$',
  '+977-1-4410388',
  NULL,
  'Experience traditional Nepali thali with live cultural dance!',
  true
);
